using System.Collections.Generic;

namespace MovieSuggestionApp
{
    public class Movie
    {
        public int Id { get; set; }
        public string Title { get; set; } = string.Empty;
        public int Year { get; set; }
        public List<string> Genre { get; set; } = new();
        public double Rating { get; set; }
        public string Plot { get; set; } = string.Empty;
        public string Director { get; set; } = string.Empty;
        public string Runtime { get; set; } = string.Empty;
        public string PosterUrl { get; set; } = string.Empty;
    }

    public static class MovieRepository
    {
        public static List<Movie> GetMovies()
        {
            return new List<Movie>
            {
                // ACTION MOVIES (10)
                new Movie { Id = 1, Title = "Mad Max: Fury Road", Year = 2015, Genre = new List<string> { "Action" }, Rating = 8.1, Plot = "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland.", Director = "George Miller", Runtime = "120 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BN2EwM2I5OWMtMGQyMi00Zjg1LWJkNTctZTdjYTA4OGUwZjMyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg" },
                new Movie { Id = 2, Title = "The Dark Knight", Year = 2008, Genre = new List<string> { "Action" }, Rating = 9.0, Plot = "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest tests.", Director = "Christopher Nolan", Runtime = "152 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_SX300.jpg" },
                new Movie { Id = 3, Title = "Gladiator", Year = 2000, Genre = new List<string> { "Action" }, Rating = 8.5, Plot = "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family.", Director = "Ridley Scott", Runtime = "155 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMDliMmNhNDEtODUyOS00MjNlLTgxODEtN2U3NzIxMGVkZTA1L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg" },
                new Movie { Id = 4, Title = "The Matrix", Year = 1999, Genre = new List<string> { "Action" }, Rating = 8.7, Plot = "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.", Director = "Lana Wachowski", Runtime = "136 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BNzQzOTk3OTAtNDQ0Zi00ZTVkLWI0MTEtMDllZjNkYzNjNTc4L2ltYWdlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg" },
                new Movie { Id = 5, Title = "John Wick", Year = 2014, Genre = new List<string> { "Action" }, Rating = 7.4, Plot = "An ex-hitman comes out of retirement to track down the gangsters that killed his dog and took everything from him.", Director = "Chad Stahelski", Runtime = "101 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTU2NjA1ODgzMF5BMl5BanBnXkFtZTgwMTM2MTI4MjE@._V1_SX300.jpg" },
                new Movie { Id = 6, Title = "Die Hard", Year = 1988, Genre = new List<string> { "Action" }, Rating = 8.2, Plot = "A New York City police officer tries to save his estranged wife and several others taken hostage by terrorists during a Christmas party.", Director = "John McTiernan", Runtime = "132 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BZjRlNDUxZjAtOGQ4OC00OTNlLTgxNmQtYTBmMDgwZmNmNjkxXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg" },
                new Movie { Id = 7, Title = "The Raid", Year = 2011, Genre = new List<string> { "Action" }, Rating = 7.6, Plot = "A S.W.A.T. team becomes trapped in a tenement run by a ruthless mobster and his army of killers and thugs.", Director = "Gareth Evans", Runtime = "101 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BYzNmYzg1Y2YtYWJkZS00YjZhLTgzMjYtZDhiYjUyNjM4ZDY4XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg" },
                new Movie { Id = 8, Title = "Mission: Impossible - Fallout", Year = 2018, Genre = new List<string> { "Action" }, Rating = 7.7, Plot = "Ethan Hunt and his IMF team must track down a dangerous weapon that has fallen into the wrong hands.", Director = "Christopher McQuarrie", Runtime = "147 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTk3NDY5MTU0NV5BMl5BanBnXkFtZTgwNDI3MDE1NTM@._V1_SX300.jpg" },
                new Movie { Id = 9, Title = "Top Gun: Maverick", Year = 2022, Genre = new List<string> { "Action" }, Rating = 8.3, Plot = "After thirty years, Maverick is still pushing the envelope as a top naval aviator, training a new generation of pilots.", Director = "Joseph Kosinski", Runtime = "130 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BZWYzOGEwNTgtNWU3NS00ZTQ0LWJkODUtMmVhMjIwMjA1ZmQwXkEyXkFqcGdeQXVyMjkwOTAyMDU@._V1_SX300.jpg" },
                new Movie { Id = 10, Title = "Terminator 2: Judgment Day", Year = 1991, Genre = new List<string> { "Action" }, Rating = 8.6, Plot = "A cyborg is sent from the future to protect a boy from an advanced Terminator sent to kill him.", Director = "James Cameron", Runtime = "137 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMGU2NzRmZjUtOGUxYS00ZjdjLWEwZWItY2NlM2JhNjkxNTFmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg" },

                // DRAMA MOVIES (10)
                new Movie { Id = 11, Title = "The Shawshank Redemption", Year = 1994, Genre = new List<string> { "Drama" }, Rating = 9.3, Plot = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.", Director = "Frank Darabont", Runtime = "142 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BNDE3ODcxYzMtY2YzZC00NmNlLWJiNDMtZDViZWM2MzIxZDYwXkEyXkFqcGdeQXVyNjAwNDUxODI@._V1_SX300.jpg" },
                new Movie { Id = 12, Title = "Forrest Gump", Year = 1994, Genre = new List<string> { "Drama" }, Rating = 8.8, Plot = "The presidencies of Kennedy and Johnson, the Vietnam War, and other historical events unfold from the perspective of an Alabama man.", Director = "Robert Zemeckis", Runtime = "142 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg" },
                new Movie { Id = 13, Title = "The Green Mile", Year = 1999, Genre = new List<string> { "Drama" }, Rating = 8.6, Plot = "The lives of guards on Death Row are affected by one of their charges: a black man accused of child murder and rape.", Director = "Frank Darabont", Runtime = "189 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_SX300.jpg" },
                new Movie { Id = 14, Title = "Fight Club", Year = 1999, Genre = new List<string> { "Drama" }, Rating = 8.8, Plot = "An insomniac office worker and a devil-may-care soap maker form an underground fight club.", Director = "David Fincher", Runtime = "139 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BNDIzNDU0YzEtYzE5Ni00ZjlkLTk5ZjgtNjM3NWE4YzA3Nzk3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg" },
                new Movie { Id = 15, Title = "Schindler's List", Year = 1993, Genre = new List<string> { "Drama" }, Rating = 9.0, Plot = "In German-occupied Poland during World War II, industrialist Oskar Schindler gradually becomes concerned for his Jewish workforce.", Director = "Steven Spielberg", Runtime = "195 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BNDE4OTMxMTctNmRhYy00NWE2LTg3YzItYTk3M2UwOTU5Njg4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg" },
                new Movie { Id = 16, Title = "Good Will Hunting", Year = 1997, Genre = new List<string> { "Drama" }, Rating = 8.3, Plot = "A janitor at MIT has a gift for mathematics, but needs help from a psychologist to find direction in his life.", Director = "Gus Van Sant", Runtime = "126 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BOTI0MzcxMTYtZDVkMy00NjY1LTgyMTYtZmUxN2M3NmQ2NWJhXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg" },
                new Movie { Id = 17, Title = "A Beautiful Mind", Year = 2001, Genre = new List<string> { "Drama" }, Rating = 8.2, Plot = "After John Nash, a brilliant but asocial mathematician, accepts secret work in cryptography, his life takes a turn for the worse.", Director = "Ron Howard", Runtime = "135 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMzcwYWFkYzktZjAzNC00OGY1LWI4YTgtNzc5MzVjMDVmNjY0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg" },
                new Movie { Id = 18, Title = "The Pianist", Year = 2002, Genre = new List<string> { "Drama" }, Rating = 8.5, Plot = "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto during World War II.", Director = "Roman Polanski", Runtime = "150 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BOWRiZDIxZjktMTA1NC00MDQ2LWEzMjUtMTliZmY3NjQ3ODJiXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg" },
                new Movie { Id = 19, Title = "12 Years a Slave", Year = 2013, Genre = new List<string> { "Drama" }, Rating = 8.1, Plot = "In the antebellum United States, Solomon Northup, a free black man from upstate New York, is abducted and sold into slavery.", Director = "Steve McQueen", Runtime = "134 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMjExMTEzODkyN15BMl5BanBnXkFtZTcwNTU4NTc4OQ@@._V1_SX300.jpg" },
                new Movie { Id = 20, Title = "Room", Year = 2015, Genre = new List<string> { "Drama" }, Rating = 8.1, Plot = "A young boy and his mother, held captive in a single room, must find a way to escape and adjust to the outside world.", Director = "Lenny Abrahamson", Runtime = "118 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMjE4NzgzNzEwMl5BMl5BanBnXkFtZTgwMTMzMDE0NjE@._V1_SX300.jpg" },

                // COMEDY MOVIES (10)
                new Movie { Id = 21, Title = "The Grand Budapest Hotel", Year = 2014, Genre = new List<string> { "Comedy" }, Rating = 8.1, Plot = "A writer encounters the owner of an aging high-class hotel, who tells him of his early years serving as a lobby boy.", Director = "Wes Anderson", Runtime = "99 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMzM5NjUxOTEyMl5BMl5BanBnXkFtZTgwNjEyMDM0MDE@._V1_SX300.jpg" },
                new Movie { Id = 22, Title = "The Intouchables", Year = 2011, Genre = new List<string> { "Comedy" }, Rating = 8.5, Plot = "After he becomes a quadriplegic from a paragliding accident, an aristocrat hires a young man from the projects to be his caregiver.", Director = "Olivier Nakache", Runtime = "112 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTYxNDA3MDQwNl5BMl5BanBnXkFtZTcwNTU4Mzc1Nw@@._V1_SX300.jpg" },
                new Movie { Id = 23, Title = "Superbad", Year = 2007, Genre = new List<string> { "Comedy" }, Rating = 7.6, Plot = "Two co-dependent high school seniors are forced to deal with separation anxiety after their plan to stage a party goes awry.", Director = "Greg Mottola", Runtime = "113 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BY2VkMDg4ZTYtN2M3Yy00NWZiLWE2ODEtZjU5MjZkYWNkNGIzXkEyXkFqcGdeQXVyODY5Njk4Njc@._V1_SX300.jpg" },
                new Movie { Id = 24, Title = "The Hangover", Year = 2009, Genre = new List<string> { "Comedy" }, Rating = 7.7, Plot = "Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing.", Director = "Todd Phillips", Runtime = "100 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BNGQwZjg5YmYtY2VkNC00NzliLTljYTctNzI5NmU3MjE2ODQzXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg" },
                new Movie { Id = 25, Title = "Groundhog Day", Year = 1993, Genre = new List<string> { "Comedy" }, Rating = 8.0, Plot = "A weatherman finds himself living the same day over and over again in a small Pennsylvania town.", Director = "Harold Ramis", Runtime = "101 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BZWIxNzM5YzQtY2FmMS00Yjc3LWI1ZjUtNGVjMjMzZTIxZTIxXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg" },
                new Movie { Id = 26, Title = "Bridesmaids", Year = 2011, Genre = new List<string> { "Comedy" }, Rating = 6.8, Plot = "Competition between the maid of honor and a bridesmaid threatens to upend the life of an out-of-work pastry chef.", Director = "Paul Feig", Runtime = "125 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMjAyOTMyMzUxNl5BMl5BanBnXkFtZTcwODI4MzE0NA@@._V1_SX300.jpg" },
                new Movie { Id = 27, Title = "21 Jump Street", Year = 2012, Genre = new List<string> { "Comedy" }, Rating = 7.2, Plot = "Two underachieving cops are sent back to high school to blend in and bring down a synthetic drug ring.", Director = "Phil Lord", Runtime = "109 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTc3NjM4MzQtMWI4NS00MjJjLTk0ZTctZTgxNGQxMGY0NDdjXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg" },
                new Movie { Id = 28, Title = "Palm Springs", Year = 2020, Genre = new List<string> { "Comedy" }, Rating = 7.4, Plot = "Two strangers stuck in a time loop must live the same day over and over again until they figure out how to escape.", Director = "Max Barbakow", Runtime = "90 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BN2E2ZmFiYTEtODg1Yi00MjZjLTkwNmUtZDYxMjVlNGU3ZTRlXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg" },
                new Movie { Id = 29, Title = "Scott Pilgrim vs. the World", Year = 2010, Genre = new List<string> { "Comedy" }, Rating = 7.6, Plot = "In a battle to win the heart of the girl of his dreams, Scott Pilgrim must defeat her seven evil exes.", Director = "Edgar Wright", Runtime = "112 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTkwNTczNTMyOF5BMl5BanBnXkFtZTcwNzUxOTUyMw@@._V1_SX300.jpg" },
                new Movie { Id = 30, Title = "Jojo Rabbit", Year = 2019, Genre = new List<string> { "Comedy" }, Rating = 7.9, Plot = "A young German boy whose imaginary friend is Adolf Hitler must reconsider his beliefs after he discovers his mother is hiding a Jewish girl.", Director = "Taika Waititi", Runtime = "108 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BZjU0Yzk2MzEtMjAzYy00MzY0LTg2YmItM2RkNzdkY2ZhN2JkXkEyXkFqcGdeQXVyNDg4NjY5OTQ@._V1_SX300.jpg" },

                // SCI-FI MOVIES (10)
                new Movie { Id = 31, Title = "Inception", Year = 2010, Genre = new List<string> { "Sci-Fi" }, Rating = 8.8, Plot = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea.", Director = "Christopher Nolan", Runtime = "148 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_SX300.jpg" },
                new Movie { Id = 32, Title = "Interstellar", Year = 2014, Genre = new List<string> { "Sci-Fi" }, Rating = 8.6, Plot = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.", Director = "Christopher Nolan", Runtime = "169 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BZjdkOTU3MDktN2IxOS00OGEyLWFmMjktY2FiMmZkNWIyODZiXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg" },
                new Movie { Id = 33, Title = "Arrival", Year = 2016, Genre = new List<string> { "Sci-Fi" }, Rating = 7.9, Plot = "A linguist works with the military to communicate with alien lifeforms after twelve mysterious spacecraft appear around the world.", Director = "Denis Villeneuve", Runtime = "116 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTExMzU0ODcxNDheQTJeQWpwZ15BbWU4MDE1OTI4MzAy._V1_SX300.jpg" },
                new Movie { Id = 34, Title = "Blade Runner 2049", Year = 2017, Genre = new List<string> { "Sci-Fi" }, Rating = 8.0, Plot = "A young blade runner's discovery of a long-buried secret leads him to track down former blade runner Rick Deckard.", Director = "Denis Villeneuve", Runtime = "164 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BNzA1Njg4NzYxOV5BMl5BanBnXkFtZTgwODk5NjU3MzI@._V1_SX300.jpg" },
                new Movie { Id = 35, Title = "The Martian", Year = 2015, Genre = new List<string> { "Sci-Fi" }, Rating = 8.0, Plot = "An astronaut becomes stranded on Mars after his team assumes him dead, and must rely on his ingenuity to survive.", Director = "Ridley Scott", Runtime = "144 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTc2MTQ3MDA1Nl5BMl5BanBnXkFtZTgwODA3OTI4NjE@._V1_SX300.jpg" },
                new Movie { Id = 36, Title = "Dune", Year = 2021, Genre = new List<string> { "Sci-Fi" }, Rating = 8.0, Plot = "Feature adaptation of Frank Herbert's science fiction novel about a duke's son leading desert warriors against the galactic emperor.", Director = "Denis Villeneuve", Runtime = "155 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BN2FjNmEyNWMtYzM0ZS00NjIyLTg5YzYtYThlMGVjNzE1OGViXkEyXkFqcGdeQXVyMTkxNjUyNQ@@._V1_SX300.jpg" },
                new Movie { Id = 37, Title = "Ex Machina", Year = 2014, Genre = new List<string> { "Sci-Fi" }, Rating = 7.7, Plot = "A young programmer is selected to participate in a groundbreaking experiment in synthetic intelligence.", Director = "Alex Garland", Runtime = "108 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTUxNzc0OTIxMV5BMl5BanBnXkFtZTgwNDI3NzU2NDE@._V1_SX300.jpg" },
                new Movie { Id = 38, Title = "Her", Year = 2013, Genre = new List<string> { "Sci-Fi" }, Rating = 8.0, Plot = "In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.", Director = "Spike Jonze", Runtime = "126 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMjA1Nzk0OTM2OF5BMl5BanBnXkFtZTgwNjU2NjEwMDE@._V1_SX300.jpg" },
                new Movie { Id = 39, Title = "Edge of Tomorrow", Year = 2014, Genre = new List<string> { "Sci-Fi" }, Rating = 7.9, Plot = "A soldier fighting aliens gets caught in a time loop of his last day in battle. He teams up with a Special Forces warrior.", Director = "Doug Liman", Runtime = "113 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTc5OTk4MTM3M15BMl5BanBnXkFtZTgwODcxNjg3MDE@._V1_SX300.jpg" },
                new Movie { Id = 40, Title = "District 9", Year = 2009, Genre = new List<string> { "Sci-Fi" }, Rating = 7.9, Plot = "Violence ensues after an extraterrestrial race forced to live in slum-like conditions on Earth finds a kindred spirit in a government agent.", Director = "Neill Blomkamp", Runtime = "112 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BYmQ4ZjEwODItZDJlZi00MjA5LWU4YzItN2MwMjk2MWZkMjRjXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg" },

                // THRILLER MOVIES (10)
                new Movie { Id = 41, Title = "The Silence of the Lambs", Year = 1991, Genre = new List<string> { "Thriller" }, Rating = 8.6, Plot = "A young FBI cadet must receive the help of an incarcerated cannibal killer to catch another serial killer.", Director = "Jonathan Demme", Runtime = "118 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg" },
                new Movie { Id = 42, Title = "Se7en", Year = 1995, Genre = new List<string> { "Thriller" }, Rating = 8.6, Plot = "Two detectives hunt a serial killer who uses the seven deadly sins as his motives.", Director = "David Fincher", Runtime = "127 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BOTUwODM5MTctZjczMi00OTk4LTg3NWUtNmVhMTAzNTNjYjcyXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg" },
                new Movie { Id = 43, Title = "Shutter Island", Year = 2010, Genre = new List<string> { "Thriller" }, Rating = 8.2, Plot = "A U.S. Marshal investigates the disappearance of a murderer who escaped from a hospital for the criminally insane.", Director = "Martin Scorsese", Runtime = "138 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BYzhiNDkyNzktNTZmYS00ZTBkLTk2MDAtM2U0YjU1MzgxZjgzXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg" },
                new Movie { Id = 44, Title = "Gone Girl", Year = 2014, Genre = new List<string> { "Thriller" }, Rating = 8.1, Plot = "With his wife's disappearance having become the focus of an intense media circus, a man sees the spotlight turned on him.", Director = "David Fincher", Runtime = "149 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTk0MDQ3MzAzOV5BMl5BanBnXkFtZTgwNzI1NzE3MjE@._V1_SX300.jpg" },
                new Movie { Id = 45, Title = "The Prestige", Year = 2006, Genre = new List<string> { "Thriller" }, Rating = 8.5, Plot = "After a tragic accident, two stage magicians engage in a battle to create the ultimate illusion while sacrificing everything.", Director = "Christopher Nolan", Runtime = "130 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMjA4NDI0MTIxNF5BMl5BanBnXkFtZTYwNTM0MzY2._V1_SX300.jpg" },
                new Movie { Id = 46, Title = "Parasite", Year = 2019, Genre = new List<string> { "Thriller" }, Rating = 8.6, Plot = "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.", Director = "Bong Joon Ho", Runtime = "132 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_SX300.jpg" },
                new Movie { Id = 47, Title = "Prisoners", Year = 2013, Genre = new List<string> { "Thriller" }, Rating = 8.1, Plot = "When his daughter goes missing, a desperate father takes matters into his own hands while a detective pursues multiple leads.", Director = "Denis Villeneuve", Runtime = "153 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTg0NTIzMjQ1NV5BMl5BanBnXkFtZTcwNDc3MzM5OQ@@._V1_SX300.jpg" },
                new Movie { Id = 48, Title = "Nightcrawler", Year = 2014, Genre = new List<string> { "Thriller" }, Rating = 7.8, Plot = "When Louis Bloom, a con man desperate for work, muscles into the world of L.A. crime journalism, he blurs the line between observer and participant.", Director = "Dan Gilroy", Runtime = "117 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BN2U1YzdhYWMtZWUzMi00OWI1LWFkM2ItNWVjM2YxMGQ2MmNhXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg" },
                new Movie { Id = 49, Title = "No Country for Old Men", Year = 2007, Genre = new List<string> { "Thriller" }, Rating = 8.2, Plot = "Violence and mayhem ensue after a hunter stumbles upon a drug deal gone wrong and more than two million dollars in cash.", Director = "Ethan Coen", Runtime = "122 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMjA5Njk3MjM4OV5BMl5BanBnXkFtZTcwMTc5MTE1MQ@@._V1_SX300.jpg" },
                new Movie { Id = 50, Title = "Zodiac", Year = 2007, Genre = new List<string> { "Thriller" }, Rating = 7.7, Plot = "Between 1968 and 1983, a San Francisco cartoonist becomes an amateur detective obsessed with tracking down the Zodiac Killer.", Director = "David Fincher", Runtime = "157 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BN2UwNDc5NmEtNjVjZS00OTI5LWE5YjctMWM3ZjBiZGYwMGI2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg" },

                // HORROR MOVIES (10)
                new Movie { Id = 51, Title = "Get Out", Year = 2017, Genre = new List<string> { "Horror" }, Rating = 7.7, Plot = "A young African-American visits his white girlfriend's parents for the weekend, where his simmering uneasiness becomes real.", Director = "Jordan Peele", Runtime = "104 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BYzQzOTQzYjAtNDQ5ZS00YjQ5LTg3ZDUtZTRmZGEwMGI2YTJjXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg" },
                new Movie { Id = 52, Title = "A Quiet Place", Year = 2018, Genre = new List<string> { "Horror" }, Rating = 7.5, Plot = "In a post-apocalyptic world, a family is forced to live in silence while hiding from monsters with ultra-sensitive hearing.", Director = "John Krasinski", Runtime = "90 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMjI0MDMzNTQ0M15BMl5BanBnXkFtZTgwMTM5NzM3NDM@._V1_SX300.jpg" },
                new Movie { Id = 53, Title = "The Conjuring", Year = 2013, Genre = new List<string> { "Horror" }, Rating = 7.5, Plot = "Paranormal investigators work to help a family terrorized by a dark presence in their farmhouse.", Director = "James Wan", Runtime = "112 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTM3NjA1NDMyMV5BMl5BanBnXkFtZTcwMDQzNDMzOQ@@._V1_SX300.jpg" },
                new Movie { Id = 54, Title = "Hereditary", Year = 2018, Genre = new List<string> { "Horror" }, Rating = 7.3, Plot = "After the family matriarch passes away, a grieving family is haunted by tragic and disturbing occurrences.", Director = "Ari Aster", Runtime = "127 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BOTU5MDg3OGItZWQ1Ny00ZGVmLTg2YTUtMzBkYzQ1YWIwZjlhXkEyXkFqcGdeQXVyNTAzMTY4MDA@._V1_SX300.jpg" },
                new Movie { Id = 55, Title = "The Shining", Year = 1980, Genre = new List<string> { "Horror" }, Rating = 8.4, Plot = "A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence.", Director = "Stanley Kubrick", Runtime = "146 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BZWFlYmY2MGEtZjVkYS00YzU4LTg0YjQtYzY1ZGE3NTA5NGQxXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg" },
                new Movie { Id = 56, Title = "The Exorcist", Year = 1973, Genre = new List<string> { "Horror" }, Rating = 8.1, Plot = "When a young girl is possessed by a mysterious entity, her mother seeks the help of two priests to save her daughter.", Director = "William Friedkin", Runtime = "122 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BYWFlZGY2NDktY2ZjOS00ZWNkLTg0ZDAtZDY4MTM1ODU4ZjljXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg" },
                new Movie { Id = 57, Title = "It", Year = 2017, Genre = new List<string> { "Horror" }, Rating = 7.3, Plot = "In the summer of 1989, a group of bullied kids band together to destroy a shapeshifting monster that disguises itself as a clown.", Director = "Andy Muschietti", Runtime = "135 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BZDVkZmI0YzAtNzdjYi00ZjhhLWE1ODEtMWMzMWMzNDA0NmQ4XkEyXkFqcGdeQXVyNzYzODM3Mzg@._V1_SX300.jpg" },
                new Movie { Id = 58, Title = "Midsommar", Year = 2019, Genre = new List<string> { "Horror" }, Rating = 7.1, Plot = "A couple travels to Sweden to visit a rural hometown's fabled mid-summer festival, which turns into a nightmare.", Director = "Ari Aster", Runtime = "148 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMzQxNzQzOTQwM15BMl5BanBnXkFtZTgwMDQ2NjI5NzM@._V1_SX300.jpg" },
                new Movie { Id = 59, Title = "The Witch", Year = 2015, Genre = new List<string> { "Horror" }, Rating = 7.0, Plot = "A family in 1630s New England is torn apart by the forces of witchcraft, black magic, and possession.", Director = "Robert Eggers", Runtime = "92 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTUyNzkwMzAxOF5BMl5BanBnXkFtZTgwMzc1OTk1NjE@._V1_SX300.jpg" },
                new Movie { Id = 60, Title = "The Ring", Year = 2002, Genre = new List<string> { "Horror" }, Rating = 7.1, Plot = "A journalist must investigate a mysterious videotape which seems to cause the death of anyone one week after viewing it.", Director = "Gore Verbinski", Runtime = "115 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BNDA2NTg2NjE4Ml5BMl5BanBnXkFtZTYwMjYxMDg5._V1_SX300.jpg" },

                // CRIME MOVIES (10)
                new Movie { Id = 61, Title = "The Godfather", Year = 1972, Genre = new List<string> { "Crime" }, Rating = 9.2, Plot = "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.", Director = "Francis Ford Coppola", Runtime = "175 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg" },
                new Movie { Id = 62, Title = "Goodfellas", Year = 1990, Genre = new List<string> { "Crime" }, Rating = 8.7, Plot = "The story of Henry Hill and his life in the mob, covering his relationship with his wife and his partners in crime.", Director = "Martin Scorsese", Runtime = "145 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg" },
                new Movie { Id = 63, Title = "Pulp Fiction", Year = 1994, Genre = new List<string> { "Crime" }, Rating = 8.9, Plot = "The lives of two mob hitmen, a boxer, a gangster and his wife intertwine in four tales of violence and redemption.", Director = "Quentin Tarantino", Runtime = "154 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg" },
                new Movie { Id = 64, Title = "The Departed", Year = 2006, Genre = new List<string> { "Crime" }, Rating = 8.5, Plot = "An undercover cop and a mole in the police attempt to identify each other while infiltrating an Irish gang in Boston.", Director = "Martin Scorsese", Runtime = "151 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTI1MTY2OTIxNV5BMl5BanBnXkFtZTYwNjQ4NjY3._V1_SX300.jpg" },
                new Movie { Id = 65, Title = "The Wolf of Wall Street", Year = 2013, Genre = new List<string> { "Crime" }, Rating = 8.2, Plot = "Based on the true story of Jordan Belfort, from his rise to a wealthy stock-broker living the high life to his fall involving crime.", Director = "Martin Scorsese", Runtime = "180 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMjIxMjgxNTk0MF5BMl5BanBnXkFtZTgwNjIyOTg2MDE@._V1_SX300.jpg" },
                new Movie { Id = 66, Title = "Heat", Year = 1995, Genre = new List<string> { "Crime" }, Rating = 8.3, Plot = "A group of professional bank robbers start to feel the heat from police when they unknowingly leave a clue at their latest heist.", Director = "Michael Mann", Runtime = "170 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BNGMwNzUwNjYtZWM5NS00YzMyLWI4NjAtNjM0ZDBiMzE1YWExXkEyXkFqcGdeQXVyNDk3NzU2MTQ@._V1_SX300.jpg" },
                new Movie { Id = 67, Title = "Casino", Year = 1995, Genre = new List<string> { "Crime" }, Rating = 8.2, Plot = "A tale of greed, deception, money, power, and murder occur between two best friends and a trophy wife.", Director = "Martin Scorsese", Runtime = "178 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTcxOWYzNDYtYmM4YS00N2NkLTk0NTAtNjg1ODgwZjAxYzI3XkEyXkFqcGdeQXVyNTA4NzY1MzY@._V1_SX300.jpg" },
                new Movie { Id = 68, Title = "Scarface", Year = 1983, Genre = new List<string> { "Crime" }, Rating = 8.3, Plot = "In 1980 Miami, a determined Cuban immigrant takes over a drug cartel and succumbs to greed.", Director = "Brian De Palma", Runtime = "170 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BNjdjNGQ4NDEtNTEwYS00MTgxLTliYzQtYzE2ZDRiZjFhZmNlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg" },
                new Movie { Id = 69, Title = "Reservoir Dogs", Year = 1992, Genre = new List<string> { "Crime" }, Rating = 8.3, Plot = "When a simple jewelry heist goes horribly wrong, the surviving criminals begin to suspect that one of them is a police informant.", Director = "Quentin Tarantino", Runtime = "99 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BZmExNmEwYWItYmQzOS00YjA5LTk2MjktZjEyZDE1Y2QxNjA1XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg" },
                new Movie { Id = 70, Title = "Knives Out", Year = 2019, Genre = new List<string> { "Crime" }, Rating = 7.9, Plot = "A detective investigates the death of a patriarch of an eccentric, combative family.", Director = "Rian Johnson", Runtime = "130 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMGUwZjliMTAtNzAxZi00MWNiLWE2NzgtZGUxMGQxZjhhNDRiXkEyXkFqcGdeQXVyNjU1NzU3MzE@._V1_SX300.jpg" },

                // ANIMATION MOVIES (10)
                new Movie { Id = 71, Title = "Spider-Man: Into the Spider-Verse", Year = 2018, Genre = new List<string> { "Animation" }, Rating = 8.4, Plot = "Teen Miles Morales becomes Spider-Man of his reality, crossing paths with five counterparts from other dimensions.", Director = "Bob Persichetti", Runtime = "117 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMjMwNDkxMTgzOF5BMl5BanBnXkFtZTgwNTkwNTQ3NjM@._V1_SX300.jpg" },
                new Movie { Id = 72, Title = "Spirited Away", Year = 2001, Genre = new List<string> { "Animation" }, Rating = 8.6, Plot = "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods and witches.", Director = "Hayao Miyazaki", Runtime = "125 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMjlmZmI5MDctNDE2YS00YWE0LWE5ZWItZDBhYWQ0NTcxNWRhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg" },
                new Movie { Id = 73, Title = "WALL·E", Year = 2008, Genre = new List<string> { "Animation" }, Rating = 8.4, Plot = "In the distant future, a small waste-collecting robot inadvertently embarks on a space journey that will decide humanity's fate.", Director = "Andrew Stanton", Runtime = "98 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMjExMTg5OTU0NF5BMl5BanBnXkFtZTcwMjMxMzMzMw@@._V1_SX300.jpg" },
                new Movie { Id = 74, Title = "Coco", Year = 2017, Genre = new List<string> { "Animation" }, Rating = 8.4, Plot = "Aspiring musician Miguel confronts his family's ancestral ban on music and enters the Land of the Dead to find his great-great-grandfather.", Director = "Lee Unkrich", Runtime = "105 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BYjQ5NjM0Y2YtNjZkNC00ZDhkLWJjMWItN2QyNzFkMDE3ZjAxXkEyXkFqcGdeQXVyODIxMzk5NjA@._V1_SX300.jpg" },
                new Movie { Id = 75, Title = "The Lion King", Year = 1994, Genre = new List<string> { "Animation" }, Rating = 8.5, Plot = "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.", Director = "Roger Allers", Runtime = "88 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BYTYxNGMyZTYtMjE3MS00MzNjLWFjNmYtMDk3N2FmM2JiM2M1XkEyXkFqcGdeQXVyNjY5NDU4NzI@._V1_SX300.jpg" },
                new Movie { Id = 76, Title = "Toy Story", Year = 1995, Genre = new List<string> { "Animation" }, Rating = 8.3, Plot = "A cowboy doll is profoundly threatened when a new spaceman figure supplants him as top toy in a boy's room.", Director = "John Lasseter", Runtime = "81 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMDU2ZWJlMjktMTRhMy00ZTA5LWEzNDgtYmNmZTEwZTViZWJkXkEyXkFqcGdeQXVyNDQ2OTk4MzI@._V1_SX300.jpg" },
                new Movie { Id = 77, Title = "Finding Nemo", Year = 2003, Genre = new List<string> { "Animation" }, Rating = 8.2, Plot = "After his son is captured in the Great Barrier Reef, a timid clownfish sets out on a journey to bring him home.", Director = "Andrew Stanton", Runtime = "100 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BZjMxYzExOWYtNGMwYi00NzJkLWFmOGUtNmYwZmY0Y2E3OWViXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg" },
                new Movie { Id = 78, Title = "Inside Out", Year = 2015, Genre = new List<string> { "Animation" }, Rating = 8.1, Plot = "After young Riley is uprooted from her Midwest life and moved to San Francisco, her emotions conflict on how best to navigate a new city.", Director = "Pete Docter", Runtime = "95 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BOTgxMDQwMDk0OF5BMl5BanBnXkFtZTgwNjU5OTg2NDE@._V1_SX300.jpg" },
                new Movie { Id = 79, Title = "How to Train Your Dragon", Year = 2010, Genre = new List<string> { "Animation" }, Rating = 8.1, Plot = "A hapless young Viking who aspires to hunt dragons becomes the unlikely friend of a young dragon himself.", Director = "Dean DeBlois", Runtime = "98 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMjA5NDQyMjc2NF5BMl5BanBnXkFtZTcwMjg5ODcyMw@@._V1_SX300.jpg" },
                new Movie { Id = 80, Title = "Your Name", Year = 2016, Genre = new List<string> { "Animation" }, Rating = 8.4, Plot = "Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?", Director = "Makoto Shinkai", Runtime = "106 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BODRmZDVmNzUtZDA4ZC00NjhkLWI2M2UtN2M0ZDIzNDcxYThjL2ltYWdlXkEyXkFqcGdeQXVyNTk0MzMzODA@._V1_SX300.jpg" },

                // MYSTERY MOVIES (10)
                new Movie { Id = 81, Title = "Knives Out", Year = 2019, Genre = new List<string> { "Mystery" }, Rating = 7.9, Plot = "A detective investigates the death of a patriarch of an eccentric, combative family.", Director = "Rian Johnson", Runtime = "130 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMGUwZjliMTAtNzAxZi00MWNiLWE2NzgtZGUxMGQxZjhhNDRiXkEyXkFqcGdeQXVyNjU1NzU3MzE@._V1_SX300.jpg" },
                new Movie { Id = 82, Title = "Rear Window", Year = 1954, Genre = new List<string> { "Mystery" }, Rating = 8.5, Plot = "A wheelchair-bound photographer spies on his neighbors from his apartment window and becomes convinced one of them has committed murder.", Director = "Alfred Hitchcock", Runtime = "112 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BNGUxYWM3M2MtMGM3Mi00ZmRiLWE0NGQtZjE5ODI2OTJhNTU0XkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg" },
                new Movie { Id = 83, Title = "The Usual Suspects", Year = 1995, Genre = new List<string> { "Mystery" }, Rating = 8.5, Plot = "A sole survivor tells of the twisty events leading up to a horrific gun battle on a boat, which began when five criminals met at a police lineup.", Director = "Bryan Singer", Runtime = "106 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BYTViNjMyNmUtNDFkNC00ZDRlLThmMDUtZDU2YWE4NGI2ZjVmXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg" },
                new Movie { Id = 84, Title = "Chinatown", Year = 1974, Genre = new List<string> { "Mystery" }, Rating = 8.1, Plot = "A private detective hired to expose an adulterer in 1930s Los Angeles finds himself caught up in a web of deceit, corruption, and murder.", Director = "Roman Polanski", Runtime = "130 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMjJkMDZhYzItZTFhMi00ZGI4LThlNTAtZDNlNWJjMzRhNzE3XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg" },
                new Movie { Id = 85, Title = "Memento", Year = 2000, Genre = new List<string> { "Mystery" }, Rating = 8.4, Plot = "A man with short-term memory loss attempts to track down his wife's murderer using notes and tattoos on his body.", Director = "Christopher Nolan", Runtime = "113 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BZTcyNjk1MjgtOWI3Mi00YzQwLWI5MTktMzY4ZmI2NDAyNzYzXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg" },
                new Movie { Id = 86, Title = "The Girl with the Dragon Tattoo", Year = 2011, Genre = new List<string> { "Mystery" }, Rating = 7.8, Plot = "A journalist is aided by a young female hacker in his search for the killer of a woman who has been dead for forty years.", Director = "David Fincher", Runtime = "158 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMTczNDk4NTQ0OV5BMl5BanBnXkFtZTcwNDAxMDgxNw@@._V1_SX300.jpg" },
                new Movie { Id = 87, Title = "Identity", Year = 2003, Genre = new List<string> { "Mystery" }, Rating = 7.3, Plot = "Stranded at a desolate Nevada motel during a nasty rain storm, ten strangers become acquainted with each other when they realize that they're being killed off one by one.", Director = "James Mangold", Runtime = "90 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMjM4MDI2NDY5Ml5BMl5BanBnXkFtZTYwMjQ4MTc3._V1_SX300.jpg" },
                new Movie { Id = 88, Title = "Clue", Year = 1985, Genre = new List<string> { "Mystery" }, Rating = 7.2, Plot = "Six guests are anonymously invited to a strange mansion for dinner, but after their host is killed, they must cooperate to identify the murderer.", Director = "Jonathan Lynn", Runtime = "94 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BNmY4ODVmYmItZGRkMy00NWQxLWE4NjItMzY4NzU4OTk0NjI2XkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg" },
                new Movie { Id = 89, Title = "Glass Onion", Year = 2022, Genre = new List<string> { "Mystery" }, Rating = 7.2, Plot = "Tech billionaire Miles Bron invites friends for a getaway on his private Greek island, where a murder investigation reveals layers of secrets.", Director = "Rian Johnson", Runtime = "139 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BYzM4MWQyODItYzhmZS00ZWFhLWE4NzgtMzI1ZTZkYjk3MzBkXkEyXkFqcGdeQXVyMTY5Nzc4MDY@._V1_SX300.jpg" },
                new Movie { Id = 90, Title = "L.A. Confidential", Year = 1997, Genre = new List<string> { "Mystery" }, Rating = 8.2, Plot = "As corruption grows in 1950s Los Angeles, three policemen investigate a series of murders with their own brand of justice.", Director = "Curtis Hanson", Runtime = "138 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMDQ2YzEyZGItYWRhOS00MjBmLTkzMDUtMTdjYzkyMmQxZTJlXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg" },

                // ADVENTURE MOVIES (10)
                new Movie { Id = 91, Title = "Indiana Jones and the Last Crusade", Year = 1989, Genre = new List<string> { "Adventure" }, Rating = 8.2, Plot = "Indiana Jones and his father must stop the Nazis from obtaining the Holy Grail, which grants immortality.", Director = "Steven Spielberg", Runtime = "127 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BY2Q0ODg4ZmItNDZiYi00ZWY5LTg2NzctNmYwZjA5OThmNzE1XkEyXkFqcGdeQXVyMjM4MzQ4OTQ@._V1_SX300.jpg" },
                new Movie { Id = 92, Title = "Jurassic Park", Year = 1993, Genre = new List<string> { "Adventure" }, Rating = 8.2, Plot = "A pragmatic paleontologist touring an almost complete theme park on an island is tasked with protecting a couple of kids.", Director = "Steven Spielberg", Runtime = "127 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMjM2MDgxMDg0Nl5BMl5BanBnXkFtZTgwNTM2OTM5NDE@._V1_SX300.jpg" },
                new Movie { Id = 93, Title = "The Lord of the Rings: The Fellowship of the Ring", Year = 2001, Genre = new List<string> { "Adventure" }, Rating = 8.8, Plot = "A young hobbit and his companions set out to destroy an ancient ring that could enable a dark lord to conquer the world.", Director = "Peter Jackson", Runtime = "178 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BN2EyZjM3NzUtNWUzMi00MTgxLWI0NTctMzY4M2VlOTdjZWRiXkEyXkFqcGdeQXVyNDUzOTQ5MjY@._V1_SX300.jpg" },
                new Movie { Id = 94, Title = "Pirates of the Caribbean: The Curse of the Black Pearl", Year = 2003, Genre = new List<string> { "Adventure" }, Rating = 8.1, Plot = "Blacksmith Will Turner teams up with eccentric pirate Jack Sparrow to save his love from Jack's former crew.", Director = "Gore Verbinski", Runtime = "143 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BNGYyZGM5MGMtYTY2Ni00M2Y1LWIzNjQtYWUzM2VlNGVhMDNhXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg" },
                new Movie { Id = 95, Title = "Avatar", Year = 2009, Genre = new List<string> { "Adventure" }, Rating = 7.9, Plot = "A paraplegic Marine dispatched to the moon Pandora becomes torn between following his orders and protecting the world he feels is his home.", Director = "James Cameron", Runtime = "162 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BZDA0OGQxNTItMDZkMC00N2UyLTg3MzMtYTJmNjg3Nzk5MzRiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg" },
                new Movie { Id = 96, Title = "Life of Pi", Year = 2012, Genre = new List<string> { "Adventure" }, Rating = 7.9, Plot = "A young man survives a disaster at sea and is hurtled into an epic journey of adventure and discovery with a Bengal tiger.", Director = "Ang Lee", Runtime = "127 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BNTg2OTY2ODg5OF5BMl5BanBnXkFtZTcwODM5MTYxOA@@._V1_SX300.jpg" },
                new Movie { Id = 97, Title = "The Revenant", Year = 2015, Genre = new List<string> { "Adventure" }, Rating = 8.0, Plot = "A frontiersman on a fur trading expedition in the 1820s fights for survival after being mauled by a bear and left for dead.", Director = "Alejandro G. Iñárritu", Runtime = "156 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMDE5OWMzM2QtOTU2ZS00NzAyLWI2MDEtOTRlYjIxZGM0OWRjXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_SX300.jpg" },
                new Movie { Id = 98, Title = "The Princess Bride", Year = 1987, Genre = new List<string> { "Adventure" }, Rating = 8.0, Plot = "While home sick in bed, a young boy's grandfather reads him the story of a farmboy-turned-pirate who encounters numerous obstacles.", Director = "Rob Reiner", Runtime = "98 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BMGM4M2Q5N2MtNThkZS00NTc1LTk1NTItNWEyZjJjNDRmNDk5XkEyXkFqcGdeQXVyMjA0MDQ0Mjc@._V1_SX300.jpg" },
                new Movie { Id = 99, Title = "Cast Away", Year = 2000, Genre = new List<string> { "Adventure" }, Rating = 7.8, Plot = "A FedEx executive undergoes a physical and emotional transformation after crash landing on a deserted island.", Director = "Robert Zemeckis", Runtime = "143 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BN2Y5ZTU4YjctMDRmMC00MTg4LWE1M2MtMjk4MzVmOTE4YjkzXkEyXkFqcGdeQXVyNTc1NTQxODI@._V1_SX300.jpg" },
                new Movie { Id = 100, Title = "Mad Max: Fury Road", Year = 2015, Genre = new List<string> { "Adventure" }, Rating = 8.1, Plot = "In a post-apocalyptic wasteland, a woman rebels against a tyrannical ruler in search for her homeland.", Director = "George Miller", Runtime = "120 min", PosterUrl = "https://m.media-amazon.com/images/M/MV5BN2EwM2I5OWMtMGQyMi00Zjg1LWJkNTctZTdjYTA4OGUwZjMyXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg" }
            };
        }
    }
}